info/__init__.py
# -*- coding:utf-8 -*-
__author__ = 'ChenJiaBao'
__date__ = '2018/9/20 13:48'
from flask import Flask, render_template
from config import config
from flask_sqlalchemy import SQLAlchemy
from redis import StrictRedis
from flask_wtf import CSRFProtect
from flask_session import Session
import logging
from logging.handlers import RotatingFileHandler
from flask.ext.wtf.csrf import generate_csrf
from flask_login import LoginManager


db = SQLAlchemy()
login_manager = LoginManager()
redis_store = None  # type:StrictRedis


def setup_log(congfig_name):
    # 设置日志的记录等级
    logging.basicConfig(level=config[congfig_name].LOG_LEVEL)
    # 创建日志记录器，指明日志的保存路径，每个日志文件的最大大小，保存的日志文件个数上限
    file_log_handler = RotatingFileHandler('logs/log', maxBytes=1024*1024*100, backupCount=10)
    # 创建日志记录的格式，日志等级，输入日志信息的文件名，行数日志信息
    formatter = logging.Formatter('%(levelname)s %(filename)s:%(lineno)d %(message)s')
    # 为刚才创建的日志记录器设置日志记录格式
    file_log_handler.setFormatter(formatter)
    # 为全局日志工具对象，添加日志记录器
    logging.getLogger().addHandler(file_log_handler)


def create_app(config_name):
    # 设置日志
    setup_log(config_name)
    app = Flask(__name__)

    # 加载配置
    app.config.from_object(config[config_name])

    # 初始化数据库, 通过app初始化
    db.init_app(app)
    login_manager.init_app(app)
    # 初始化redis存储对象
    global redis_store
    redis_store = StrictRedis(host=config[config_name].REDIS_HOST,
                              port=config[config_name].REDIS_PORT,
                              password=config[config_name].REDIS_PASSWORD,
                              decode_responses=True)

    # 开启csrf
    CSRFProtect(app)

    # 设置session保存位置
    Session(app)

    @app.errorhandler(404)
    def page_not_found(error):
        return render_template('news/404.html')

    @app.after_request
    def after_request(response):
        csrf_token = generate_csrf()
        response.set_cookie('csrf_token', csrf_token)
        return response

    # 注册蓝图
    from info.modules.index import index_blu
    app.register_blueprint(index_blu)

    from info.modules.passport import passport_blu
    app.register_blueprint(passport_blu)

    from info.modules.news import news_blu
    app.register_blueprint(news_blu)

    from info.modules.profile import profile_blu
    app.register_blueprint(profile_blu)

    from info.modules.admin import admin_blu
    app.register_blueprint(admin_blu)
    return app

info/modules/__init__.py
# -*- coding:utf-8 -*-
__author__ = 'ChenJiaBao'
__date__ = '2018/9/20 15:00'

info/modules/admin/__init__.py
# -*- coding:utf-8 -*-
__author__ = 'ChenJiaBao'
__date__ = '2018/10/31 20:12'
from flask import Blueprint, session, redirect, url_for, request

admin_blu = Blueprint('admin', __name__, url_prefix='/admin')
from . import views


@admin_blu.before_request
def check_admin():
    """
    校验
    :return:
    """
    is_admin = session.get('is_admin', False)
    if not is_admin and not request.url.endswith(url_for('admin.login')):
        return redirect(url_for('index.index'))

info/modules/admin/views.py
# -*- coding:utf-8 -*-
__author__ = 'ChenJiaBao'
__date__ = '2018/10/31 20:13'
from flask import render_template, request, session, redirect, url_for, g, current_app, jsonify
from . import admin_blu
from info.models import User, News, Category
from info.utils.common import user_login_data
import time
import datetime
from info.utils.response_code import RET
from info.utils.image_storage import storage
from info.constants import QINIU_DOMIN_PREFIX
from info import db


@admin_blu.route('/login', methods=['GET', 'POST'])
def login():
    """
    后台登录
    :return:
    """
    if request.method == 'GET':
        user_id = session.get('user_id', None)
        is_admin = session.get('is_admin', False)
        if user_id and is_admin:
            return redirect(url_for('admin.index'))
        return render_template('admin/login.html')
    username = request.form.get('username')
    password = request.form.get('password')
    if not all([username, password]):
        return render_template('admin/login.html', errmsg='请填写完整内容')
    try:
        user = User.query.filter(User.mobile == username, User.is_admin == True).first()
        if not user.check_passowrd(password):
            return render_template('admin/login.html', errmsg='用户名或者密码有误')
    except Exception as e:
        return render_template('admin/login.html', errmsg='未查询到用户信息')

    session['user_id'] = user.id
    session['mobile'] = user.mobile
    session['nick_name'] = user.nick_name
    session['is_admin'] = user.is_admin
    return redirect(url_for('admin.index'))


@admin_blu.route('/logout')
def logout():
    """
    后台退出
    :return:
    """
    session.pop('user_id', None)
    session.pop('mobile', None)
    session.pop('nick_name', None)
    session.pop('is_admin', None)
    return redirect(url_for('index.index'))


@admin_blu.route('/index')
@user_login_data
def index():
    """
    后台主页
    :return:
    """
    user = g.user

    return render_template('admin/index.html', user=user)


@admin_blu.route('/user_count')
def user_count():
    """
    后台用户数据显示
    :return:
    """
    total_count = 0
    mon_count = 0
    day_count = 0
    try:
        total_count = User.query.filter(User.is_admin == False).count()
    except Exception as e:
        current_app.logger.error(e)

    try:
        mon_count = User.query.filter(User.is_admin == False, User.create_time > datetime.datetime.strptime(('%d-%02d-01' % (time.localtime().tm_year, time.localtime().tm_mon)), '%Y-%m-%d')).count()
    except Exception as e:
        current_app.logger.error(e)

    try:
        day_count = User.query.filter(User.is_admin == False, User.create_time > datetime.datetime.strptime(('%d-%02d-%02d' % (time.localtime().tm_year, time.localtime().tm_mon, time.localtime().tm_mday  )), '%Y-%m-%d')).count()
    except Exception as e:
        current_app.logger.error(e)

    active_time = []
    active_count = []
    begin_today_date = datetime.datetime.strptime(('%d-%02d-%02d' % (time.localtime().tm_year, time.localtime().tm_mon, time.localtime().tm_mday)), '%Y-%m-%d')
    for i in range(0, 31):
        begin_date = begin_today_date - datetime.timedelta(days=i)
        end_date = begin_today_date - datetime.timedelta(days=i - 1)
        count = User.query.filter(User.is_admin == False, User.last_login    >= begin_date, User.last_login <= end_date).count()
        active_count.append(count)
        active_time.append(begin_date.strftime('%Y-%m-%d'))
    active_time.reverse()
    active_count.reverse()
    data = {
        'total_count': total_count,
        'mon_count': mon_count,
        'day_count': day_count,
        'active_count': active_count,
        'active_time': active_time
    }
    return render_template('admin/user_count.html', data=data)


@admin_blu.route('/user_list')
def user_list():
    """
    后台用户列表
    :return:
    """
    page = request.args.get('p', 1)
    page = int(page)
    pagination = User.query.filter(User.is_admin == False).paginate(page, 10, False)
    return render_template('admin/user_list.html', paginate=pagination)


@admin_blu.route('/news_review_list')
def news_review_list():
    """
    后台新闻审核列表
    :return:
    """
    page = request.args.get('p', 1)
    page = int(page)

    key_words = request.args.get('key_words', None)
    filters = [News.status != 0]
    if key_words:
        filters.append(News.title.contains(key_words))

    pagination = News.query.filter(*filters).order_by(News.create_time.desc()).paginate(page, 10, False)
    return render_template('admin/news_review.html', paginate=pagination)


@admin_blu.route('/news_review_detail/<int:news_id>')
def news_review_detail(news_id):
    """
    后台新闻审核详情
    :return:
    """
    news = News.query.filter(News.id == news_id).first()
    category = Category.query.filter(Category.id == news.category_id).first()
    return render_template('admin/news_review_detail.html', news=news, category=category)


@admin_blu.route('/news_review_doing', methods=["POST", 'GET'])
def news_review_doing():
    """
    新闻审核
    :return:
    """
    news_id = request.json.get('news_id')
    action = request.json.get('action')
    if not all([news_id, action]):
        return jsonify(errno=RET.PARAMERR, errmsg="参数错误")
    if action not in ('accept', 'reject'):
        return jsonify(errno=RET.PARAMERR, errmsg="参数错误")
    news = News.query.get(news_id)
    if not news:
        return jsonify(errno=RET.NODATA, errmsg="参数错误")
    if action == 'accept':
        news.status = 0
    else:
        reason = request.json.get('reason')
        if not reason:
            return jsonify(errno=RET.PARAMERR, errmsg="请输入拒绝原因")
        news.status = -1
        news.reason = reason
    return jsonify(errno=RET.OK, errmsg="ok")


@admin_blu.route('/news_edit_list')
def news_edit_list():
    """
    新闻编辑
    :return:
    """
    page = request.args.get('p', 1)
    page = int(page)
    key_words = request.args.get('key_words', None)
    filters = [News.status == 0]
    if key_words:
        filters.append(News.title.contains(key_words))

    pagination = News.query.filter(*filters).order_by(News.create_time.desc()).paginate(page, 10, False)
    return render_template('admin/news_edit.html', pagination=pagination)


@admin_blu.route('/news_edit_detail', methods=['GET', 'POST'])
def news_edit_detail():
    """
    后台新闻编辑详情
    :return:
    """

    if request.method == 'GET':
        news_id = request.args.get('news_id')
        news = News.query.filter(News.id == news_id).first()
        category = Category.query.all()
        return render_template('admin/news_edit_detail.html', news=news, category=category)
    else:
        title = request.form.get('title')
        digest = request.form.get('digest')
        content = request.form.get('content')
        index_image = request.files.get('index_image').read()
        category_id = request.form.get('category_id')
        if not all([title, content, digest, category_id]):
            return jsonify(errno=RET.PARAMERR, errmsg='请填写完整信息')
        news_id = request.form.get('news_id')
        news = News.query.filter(News.id == news_id).first()
        news.title = title
        news.digest = digest
        news.content = content
        key = storage(index_image)
        news.index_image_url = QINIU_DOMIN_PREFIX + key
        news.category_id = category_id
        return jsonify(errno=RET.OK, errmsg='ok')


@admin_blu.route('/news_category', methods=['POST', 'GET'])
def news_category():
    """
    后台新闻分类
    :return:
    """
    if request.method == 'GET':
        category = Category.query.all()
        return render_template("admin/news_type.html", category=category)
    category_name = request.json.get('name')
    category_id = request.json.get('id')
    if not category_name:
        return jsonify(errno=RET.PARAMERR, errmsg='请填写完整信息')
    if category_id:
        try:
            category_id = int(category_id)
            category = Category.query.get(category_id)
        except Exception as e:
            current_app.logger.error(e)
            return jsonify(errno=RET.PARAMERR, errmsg='参数错误')
        if not category:
            return jsonify(errno=RET.PARAMERR, errmsg='参数错误')
        category.name = category_name
    else:
        category = Category()
        category.name = category_name
        db.session.add(category)
    return jsonify(errno=RET.OK, errmsg='ok')

info/modules/index/__init__.py
# -*- coding:utf-8 -*-
__author__ = 'ChenJiaBao'
__date__ = '2018/9/20 15:01'
from flask import Blueprint

# 创建蓝图对象
index_blu = Blueprint('index', __name__)

from . import views

info/modules/index/views.py
# -*- coding:utf-8 -*-
__author__ = 'ChenJiaBao'
__date__ = '2018/9/20 15:02'
from . import index_blu
from flask import render_template, current_app, session, request, jsonify, g
from info.models import User, News, Category
from info import constants
from info.utils.response_code import RET
from info.utils.common import user_login_data


@index_blu.route('/')
@user_login_data
def index():
    """
    首页
    :return:
    """
    user = g.user
    data = {
        'user': user.to_dict() if user else None
    }

    # 右侧排行数据
    news_list = News.query.order_by(News.clicks.desc()).limit(constants.CLICK_RANK_MAX_NEWS)

    # 查询分类数据
    categories = Category.query.all()

    return render_template('news/index.html', data=data, news_list=news_list, categories=categories)


@index_blu.route('/favicon.ico')
def favicon():
    """加载网站小图标"""
    return current_app.send_static_file('news/favicon.ico')


@index_blu.route('/news_list')
def news_list():
    """
    获取首页新闻数据
    """
    cid = request.args.get('cid', '1')
    page = request.args.get('page', '1')
    per_page = request.args.get('per_page', '10')
    try:
        cid = int(cid)
        page = int(page)
        per_page = int(per_page)
    except Exception as e:
        current_app.logger.error(e)
        return jsonify(errno=RET.PARAMERR, errmsg='参数错误')
    filters = [News.status == 0]
    if cid != 1:
        filters.append(News.category_id == cid)
    try:
        page_data = News.query.filter(*filters).order_by(News.create_time.desc()).paginate(page, per_page, False)
        total_page = page_data.pages
    except Exception as e:
        current_app.logger.error(e)
        return jsonify(errno=RET.DBERR, errmsg='数据查询错误')
    news_data = []
    for news in page_data.items:
        news_data.append(news.to_basic_dict())
    return jsonify(errno=RET.OK, errmsg='ok', news_data=news_data, total_page=total_page)

info/modules/news/__init__.py
# -*- coding:utf-8 -*-
__author__ = 'ChenJiaBao'
__date__ = '2018/10/29 13:49'
from flask import Blueprint

news_blu = Blueprint('news', __name__, url_prefix='/news')

from . import views

info/modules/passport/__init__.py
# -*- coding:utf-8 -*-
__author__ = 'ChenJiaBao'
__date__ = '2018/10/22 13:50'
# 登录注册逻辑
from flask import Blueprint

passport_blu = Blueprint('passport', __name__, url_prefix='/passport')
from . import views

info/modules/profile/__init__.py
# -*- coding:utf-8 -*-
__author__ = 'ChenJiaBao'
__date__ = '2018/10/30 16:54'
from flask import Blueprint

profile_blu = Blueprint('profile', __name__, url_prefix='/user')

from . import views

info/utils/__init__.py
# -*- coding:utf-8 -*-
__author__ = 'ChenJiaBao'
__date__ = '2018/10/22 13:35'

info/templates/news/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="../../static/news/css/reset.css">
{% block custom_css %}
{% endblock %}
    <link rel="stylesheet" type="text/css" href="../../static/news/css/main.css">
    <script type="text/javascript" src="../../static/news/js/jquery-1.12.4.min.js"></script>
<script type="text/javascript" src="../../static/news/js/main.js"></script>
{% block custom_js %}
{% endblock %}
</head>
<body>
<div class="header_con">
    <div class="header">
        <a href="{{ url_for('index.index') }}" class="logo fl"><img src="../../static/news/images/logo.png" alt="logo"></a>
        <ul class="menu fl">
            {% for category in categories %}
                {% if loop.index == 1 %}
                    <li data-cid="{{ category.id }}" class="active"><a href="javascript:">{{ category.name }}</a></li>
                {% else %}
                    <li data-cid="{{ category.id }}"><a href="javascript:">{{ category.name }}</a></li>
                {% endif %}
            {% endfor %}
        </ul>
        {% if data.user %}
            <div class="user_login fr">
                <img src="{% if data.user.avatar_url %} {{ data.user.avatar_url }} {% else %}../../static/news/images/person01.png{% endif %}"
                     class="lgin_pic">
                <a href="{{ url_for('profile.user_info') }}" id="nick_name">{{ data.user.nick_name }}</a>
                <a href="{{ url_for('passport.logout') }}" >退出</a>
            </div>
        {% else %}

            <div class="user_btns fr">
                <a href="javascript:" class="login_btn">登录</a> / <a href="javascript:" class="register_btn">注册</a>
            </div>
        {% endif %}

        <!-- 用户登录后显示下面，隐藏上面 -->

    </div>
</div>

<div class="conter_con">
    {% block content %}
    {% endblock %}
    {% block sort %}
    <div class="rank_con fr">
        <div class="rank_title">
            <h3>点击排行</h3>
        </div>
        <ul class="rank_list">
            {% for news in news_list %}
                <li><span
                        class="{% if loop.index == 1 %}first{% elif loop.index == 2 %}second{% elif loop.index == 3 %}third{% endif %}">{{ loop.index }}</span><a
                        href="#">{{ news.title }}</a></li>
            {% endfor %}
        </ul>
    </div>
    {% endblock %}
</div>
<div class="footer">
    <div class="footer_links">
        <a href="">关于我们</a>
        <span>|</span>
        <a href="">联系我们</a>
        <span>|</span>
        <a href="">招聘人才</a>
        <span>|</span>
        <a href="">友情链接</a>
    </div>
    <p class="copyright">
        CopyRight © 2018 新经资讯信息技术有限公司 All Rights Reserved<br/>
        电话：010-****888 京ICP备*******8号
    </p>
</div>

<!-- 登录表单 -->
<form class="login_form_con">
    <div class="login_form">
        <div class="login_title">
            <h3>登 录</h3>
            <a href="javascript:" class="shutoff"></a>
        </div>
        <div class="form_group">
            <input id="mobile" type="text" name="mobile" autocomplete="off">
            <div class="input_tip">手机号</div>
            <div id="login-mobile-err" class="error_tip">手机号不能为空</div>
        </div>
        <div class="form_group">
            <input id="password" type="password" name="password">
            <div class="input_tip">密码(不少于6位)</div>
            <div id="login-password-err" class="error_tip">密码不能为空</div>
        </div>
        <input type="submit" name="" value="登 录" class="input_sub">
        <div class="down_link">还没有账号？<a href="javascript:" class="to_register">立即注册</a></div>
    </div>
    <div class="mask"></div>
</form>

<!-- 注册表单 -->
<form class="register_form_con">

    <div class="register_form">
        <div class="register_title">
            <h3>注 册</h3>
            <a href="javascript:" class="shutoff"></a>
        </div>
        <div class="form_group">
            <input type="text" name="mobile" autocomplete="off" id="register_mobile" class="phone_input">
            <div class="input_tip">手机号</div>
            <div id="register-mobile-err" class="error_tip">手机号不能为空</div>
        </div>
        <div class="form_group">
            <input type="text" name="code_pwd" id="imagecode" class="code_pwd">
            <div class="input_tip">图形验证码</div>
            <img src="../../static/news/images/pic_code.png" class="get_pic_code" onclick="generateImageCode()">
            <div id="register-image-code-err" class="error_tip">图形码不能为空</div>
        </div>
        <div class="form_group">
            <input type="text" name="smscode" id="smscode" class="code_pwd">
            <div class="input_tip">手机验证码</div>
            <a href="javascript:" class="get_code" onclick="sendSMSCode()">点击获取验证码</a>
            <div id="register-sms-code-err" class="error_tip">验证码不能为空</div>
        </div>
        <div class="form_group">
            <input type="password" name="password" id="register_password" class="pass_input">
            <div class="input_tip">密码(不少于6位)</div>
            <div id="register-password-err" class="error_tip">密码不能为空</div>
        </div>
        <div class="form_group2 clearfix">
            <input type="checkbox" class="agree_input" checked>
            <p>同意使用条款，并已阅读"跟帖评论自律管理承诺书"</p>
            <div class="error_tip">请勾选</div>
        </div>
        <input type="submit" name="" value="注 册" class="input_sub">
        <div class="down_link">已有账号？<a href="javascript:" class="to_login">立即登录</a></div>
    </div>
    <div class="mask"></div>
</form>
</body>
</html>

info/templates/news/detail.html
{% extends 'news/base.html' %}
{% block title %}
    文章详情页
{% endblock %}
{% block custom_js %}
    <script type="text/javascript" src="../../static/news/js/detail.js"></script>
{% endblock %}
{% block content %}
    <div class="detail_con fl">
        <h3>{{ news.title }}</h3>
        <div class="detail_about clearfix">
            <span class="time_souce fl">{{ news.create_time }} 来源: {{ news.source }}</span>
            <span class="comment fr">{{ total_comment }}</span>
        </div>

        <p class="summary">
            摘要：{{ news.digest }}
        </p>

        <h4>{{ news.title }}</h4>

        <p>
            {{ news.content|safe }}</p>

        <a href="javascript:" class="collected block-center" data-newid="{{ news.id }}"
           style="display: {% if is_collected %} block
           {% else %} none {% endif %};"><span class="out">已收藏</span><span class="over">取消收藏</span></a>
        <a href="javascript:" class="collection block-center" data-newid="{{ news.id }}"
           style="display: {% if is_collected %} none
           {% else %} block {% endif %};">收藏</a>



        {% if data.user %}
            <form action="" class="comment_form" data-newsid="{{ news.id }}">
                <div class="person_pic">

                    <img src="
                            {% if data.user.avatar_url %}{{ data.user.avatar_url }}{% else %}../../static/news/images/person01.png{% endif %}"
                         alt="用户图标">
                </div>
                <textarea placeholder="请发表您的评论" class="comment_input"></textarea>
                <input type="submit" name="" value="评 论" class="comment_sub">
            </form>
        {% else %}
            <div class="comment_form_logout">
                登录发表你的评论
            </div>
        {% endif %}





        <div class="comment_count">
            {{ total_comment }}条评论
        </div>

        <div class="comment_list_con">
            {% for comment in comments %}
                <div class="comment_list">
                    <div class="person_pic fl">
                        <img src="
                                {% if comment.user.avatar_url %}{{ comment.user.avatar_url }}{% else %}../../static/news/images/person01.png{% endif %}"
                             alt="用户图标">
                    </div>
                    <div class="user_name fl">{{ comment.user.nick_name }}</div>
                    <div class="comment_text fl">
                        {{ comment.content }}
                    </div>

                    {% if comment.parent %}
                        <div class="reply_text_con fl">
                            <div class="user_name2">{{ comment.parent.user.nick_name }}</div>
                            <div class="reply_text">
                                {{ comment.parent.content }}

                            </div>
                        </div>
                    {% endif %}

                    <div class="comment_time fl">{{ comment.create_time }}</div>
                    <a href="javascript:" class="comment_up{% if comment.is_like %} has_comment_up{% endif %} fr"
                       data-commentid="{{ comment.id }}" data-newsid="{{ news.id }}"
                       data-likecount="{{ comment.like_count }}">{% if comment.like_count > 0 %}
                        {{ comment.like_count }}
                    {% else %}
                        赞
                    {% endif %}</a>
                    <a href="javascript:" class="comment_reply fr">回复</a>
                    <from class="reply_form fl" data-commentid="{{ comment.id }}" data-newsid="{{ comment.news_id }}">
                        <textarea class="reply_input"></textarea>
                        <input type="submit" name="" value="回复" class="reply_sub fr">
                        <input type="reset" name="" value="取消" class="reply_cancel fr">
                    </from>
                </div>
            {% endfor %}
        </div>


    </div>
{% endblock %}
{% block sort %}
    <div class="rank_con fr">
        {% if author %}
            <div class="author_card">
                <a href="#" class="author_pic"><img src="http://phgbzer8s.bkt.clouddn.com/{% if author.avatar_url %}{{ author.avatar_url }}{% else %}../../static/news/images/user_pic.png{% endif %}" alt="author_pic"></a>
                <a href="#" class="author_name">{{ author.nick_name }}</a>
                <div class="author_resume">签名：{{ author.signature }}</div>
                <div class="writings"><span>总篇数</span><b>{{ total_news_count }}</b></div>
                <div class="follows"><span>粉丝</span><b>{{ followers }}</b></div>
                <a href="javascript:" class="focus fr" data-userid="{{ author.id }}" style="display: {% if is_followed %}none{% else %}block{% endif %}">关注</a>
<a href="javascript:" class="focused fr" data-userid="{{ author.id }}" style="display: {% if is_followed %}block{% else %}none{% endif %}"><span class="out">已关注</span><span class="over">取消关注</span></a>

            </div>
        {% endif %}

        <div class="rank_title">
            <h3>点击排行</h3>
        </div>
        <ul class="rank_list">
            {% for news in news_list %}
                <li><span
                        class="{% if loop.index == 1 %}first{% elif loop.index == 2 %}second{% elif loop.index == 3 %}third{% endif %}">{{ loop.index }}</span><a
                        href="#">{{ news.title }}</a></li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

info/templates/news/index.html
{% extends 'news/base.html' %}
{% block title %}
    首页-新经资讯
{% endblock %}
{% block custom_js %}
    <script type="text/javascript" src="../../static/news/js/index.js"></script>
{% endblock %}
{% block content %}
     <ul class="list_con fl">

    </ul>
{% endblock %}

info/templates/news/other.html
{% extends 'news/base.html' %}
{% block title %}
    用户概况
{% endblock %}
{% block custom_css %}
<link rel="stylesheet" type="text/css" href="../../static/news/css/jquery.pagination.css">
{% endblock %}


{% block custom_js %}
     <script type="text/javascript" src="../../static/news/js/other.js"></script>
        <script type="text/javascript" src="../../static/news/js/jquery.pagination.min.js"></script>
{% endblock %}
{% block content %}

    <div class="conter_con">
        <div class="user_menu_con fl">
            <div class="user_center_pic">
                 <img src="{% if other_user.avatar_url %}
    http://phgbzer8s.bkt.clouddn.com/{{ other_user.avatar_url }}
    {% else %}
    ../../static/news/images/user_pic.png
    {% endif %}" alt="用户图片">
            </div>
            <div class="user_center_name">{{ other_user.nick_name }}</div>

            <ul class="other_detail">
                <li>性 别：{% if other_user.gender == 'MAN' %}男{% else %}女{% endif %}</li>
                <li>签 名：{% if other_user.signature %}{{ other_user.signature }}{% else %}这个人很懒，什么都没留下{% endif %}</li>
            </ul>

            <div class="focus_other">
                <a href="javascript:" class="focus" data-userid="{{ other_user.id }}" style="display: {% if is_followed %}none
    {% else %}block
    {% endif %}">关注</a>
        <a href="javascript:" class="focused"><span class="out" data-userid="{{ other_user.id }}" style="display: {% if is_followed %}block
    {% else %}none
    {% endif %}">已关注</span><span class="over">取消关注</span></a>
            </div>

        </div>

        <div class="user_con fr">
            <div class="other_collect">
                <h3>他的文章</h3>
                <ul class="article_list">

                    <li><a href=""></a><span></span></li>


                </ul>

                <div id="pagination" class="page"></div>
                <script>
                    $(function(){
                        $("#pagination").pagination({
                            currentPage: 2,
                            totalPage: 3 ,
                            callback: function(current) {
                             getNewsList(current)
                            }
                        });
                    });
                </script>
            </div>

        </div>
    </div>
{% endblock %}
{% block sort %}
{% endblock %}